default_tex_dir: &tex_dir "tex"

downloads:
  tex_dir: *tex_dir

# TODO delete api key and proxies before commit!
pipeline:
  preprocessors:
    - name: ImagePreprocessor
      params:
        directory: "img"
        output_prefix: "page_"
    - name: PDFPreprocessor
      params:
        directory: "pdf"
        output_prefix: "page_"
  stages:
    - name: MarkerPdfTextExtractor
      params:
        output_format: "json"
        languages: "en,ru"
        force_ocr: true
        format_lines: true
    - name: MarkerPdfTablesExtractor
      params:
        output_format: "json"
        languages: "en,ru"
        force_ocr: true
        format_lines: true
    - name: FormulasExtractor
      params:
        required_symbols: [ '\\', '{', '}', '_', '^' ]
        math_keywords: [ '\\frac', '\\sqrt', '\\sum', '\\int', '\\alpha', '\\beta' ]
        cache_dir: "cache/formulas"
    - name: AIExtractor
      params:
        model:
        api_key:
        proxies:
          http:
        text: "MarkerPdfTextExtractor"
        tables: "MarkerPdfTablesExtractor"
        formulas: "FormulasExtractor"
    - name: TexExporter
      params:
        directory: *tex_dir
        output_prefix: "page_"
        result_data_key: "AIExtractor"
